This is the generalmodel.h5 file that was generated. There were some lines of errors that occured that I've added below:
3219459/3219459 [==============================] - 3120s 969us/step - loss: nan
saving model
----- Generating text after Epoch: 9

----- Diversity: 0.2

----- Generating with seed: "dhesive organ. rhythmic movements of the"

dhesive organ. rhythmic movements of the/Users/stor/PycharmProjects/Storyteller/Generator_Keras.py:122: RuntimeWarning: invalid value encountered in greater_equal
  probas = np.random.multinomial(1, preds, 1)
Traceback (most recent call last):
  File "/Users/stor/PycharmProjects/Storyteller/Generator_Keras.py", line 174, in <module>
    callbacks=[print_callback])
  File "/Users/stor/PycharmProjects/Storyteller/venv/lib/python3.6/site-packages/keras/engine/training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "/Users/stor/PycharmProjects/Storyteller/venv/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 216, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/Users/stor/PycharmProjects/Storyteller/venv/lib/python3.6/site-packages/keras/callbacks/callbacks.py", line 152, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/Users/stor/PycharmProjects/Storyteller/Generator_Keras.py", line 166, in on_epoch_end
    generateText()
  File "/Users/stor/PycharmProjects/Storyteller/Generator_Keras.py", line 147, in generateText
    next_index = sample(preds, diversity)
  File "/Users/stor/PycharmProjects/Storyteller/Generator_Keras.py", line 122, in sample
    probas = np.random.multinomial(1, preds, 1)
  File "mtrand.pyx", line 4197, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 324, in numpy.random._common.check_array_constraint
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs

Process finished with exit code 1